### ISSUE TITLE
Build WASM as Release

### ISSUE THREAD

**Issue by gfs** [microsoft/OAT#34]
Currently when you try to build release you get a linker error about Blazor.FileReader.  We need to resolve this so we can publish a trimmed Release version of OAT Wasm.

```
  Fatal error in Mono IL Linker
/Users/gabe/.nuget/packages/microsoft.aspnetcore.components.webassembly.build/3.2.1/targets/Blazor.MonoRuntime.targets(326,5): error : Unhandled exception. Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Blazor.FileReader, Version=0.11.19128.0, Culture=neutral, PublicKeyToken=null' [/Users/gabe/Documents/GitHub/OAT/OAT.Blazor/OAT.Blazor.csproj]
   ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Blazor.FileReader, Version=0.11.19128.0, Culture=neutral, PublicKeyToken=null'
     at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
     at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
     at Mono.Linker.LinkContext.ResolveReferences(AssemblyDefinition assembly)
     at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
     at Mono.Linker.Steps.LoadReferencesStep.ProcessAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
/Users/gabe/.nuget/packages/microsoft.aspnetcore.components.webassembly.build/3.2.1/targets/Blazor.MonoRuntime.targets(326,5): error : ILLink failed with exit code 134. [/Users/gabe/Documents/GitHub/OAT/OAT.Blazor/OAT.Blazor.csproj]
```

**Comment by gfs** [comment]
Appears to be https://github.com/dotnet/aspnetcore/issues/22174.
